# Generated by Django 2.1.7 on 2019-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_items_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='current',
            field=models.IntegerField(default=0),
        ),
    ]
