# Generated by Django 2.1.7 on 2019-05-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_items_itemlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='itemList',
        ),
    ]
