# Generated by Django 2.1.7 on 2019-05-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_items_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='retailers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.CharField(max_length=255)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='retailer',
            field=models.IntegerField(default=0),
        ),
    ]
