# Generated by Django 2.1.7 on 2019-05-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_items_itemlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailers',
            old_name='retailer',
            new_name='retailer_description',
        ),
    ]
