# Generated by Django 2.1.7 on 2019-05-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20190527_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item',
            new_name='item_description',
        ),
    ]
