# Generated by Django 2.1.7 on 2019-05-20 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_items_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.retailers'),
        ),
    ]
