# Generated by Django 2.1.7 on 2019-05-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_items_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='mustget',
            field=models.BooleanField(default=False),
        ),
    ]
